/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Compresion;
import Controlador.Descompresion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rodrigopeniche
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
   // ArrayList<Compresion> comp= new ArrayList<>();
    
    
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        archivomenu = new javax.swing.JMenu();
        comprimiritem = new javax.swing.JMenuItem();
        descomprimiritem = new javax.swing.JMenuItem();
        salirmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivomenu.setText("Archivo");

        comprimiritem.setText("Comprimir");
        comprimiritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprimiritemActionPerformed(evt);
            }
        });
        archivomenu.add(comprimiritem);

        descomprimiritem.setText("Descomprimir");
        descomprimiritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descomprimiritemActionPerformed(evt);
            }
        });
        archivomenu.add(descomprimiritem);

        jMenuBar1.add(archivomenu);

        salirmenu.setText("Salir");
        salirmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(salirmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descomprimiritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descomprimiritemActionPerformed
        try {
            // TODO add your handling code here:
            Descompresion descomp2 = new Descompresion("reyes.txt");
            Descompresion descomp = new Descompresion("clinton.txt");
            descomp.descomprimir();
            descomp2.descomprimir();
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_descomprimiritemActionPerformed

    private void comprimiritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprimiritemActionPerformed
        // TODO add your handling code here:
//       Compresion compresion= new Compresion();
//       comp.add(compresion);
       new VentanaCompresion().setVisible(true);
        
    }//GEN-LAST:event_comprimiritemActionPerformed

    private void salirmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirmenuMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivomenu;
    private javax.swing.JMenuItem comprimiritem;
    private javax.swing.JMenuItem descomprimiritem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu salirmenu;
    // End of variables declaration//GEN-END:variables
}
